EEAFormI9Portal/Controllers/DocumentController.cs
using EEAFormI9Portal.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using EEAFormI9Portal.Models;

namespace EEAFormI9Portal.Controllers
{
    public class DocumentController : BaseController
    {
        // GET: Document
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetDocumentDetails()
        {
            var doc = new List<DocumentCurrent>();
            doc = _IDocumentManagement.GetDocumentDetails();
            var e = Mapper.Map<List<ViewDocument>>(doc);

            return Json(e, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetDocumentDetailsByFilter(string filter)
        {
            var doc = new List<DocumentCurrent>();
            doc = _IDocumentManagement.GetDocumentDetailsByFilter(filter);
            var result = Mapper.Map<List<ViewDocument>>(doc);

            return Json(result, JsonRequestBehavior.AllowGet);
        }


        public ActionResult ViewDocumentStatusDetails()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetDocumentStatusDetails()
        {
            var doc = new List<DocumentStatu>();
            doc = _IDocumentManagement.GetDocumentStatusDetails();
            var result = Mapper.Map<List<ViewDocumentStatus>>(doc);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

EEAFormI9Portal/Controllers/EmployeeController.cs
using EEAFormI9Portal.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace EEAFormI9Portal.Controllers
{
    public class EmployeeController : BaseController
    {
        // GET: Employee
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult SendEmailPassword(string email)
        {
            var sendToEmail = email;
            if (sendToEmail != null)
            {
                var result = _IEmailManagement.SendEmailPassword(sendToEmail);
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<JsonResult> ConfirmAccount(ResetPasswordViewModel model)
        {
            //if(data != null)
            //{
            //    var result = _IUserManagement.ConfirmAccount(data);
            //}
            //return Json(true, JsonRequestBehavior.AllowGet);
            if (!ModelState.IsValid)
            {
                //return View(model);
            }
            var user1 = db.AspNetUsers.SingleOrDefault(x => x.Email == model.Email);
            var user = UserManager.FindByEmail(model.Email);
            if (user == null)
            {
                // Don't reveal that the user does not exist
                //return RedirectToAction("ResetPasswordConfirmation", "Account");
            }
            else if (model.Code == user1.TempCode)
            {
                string code = await UserManager.GeneratePasswordResetTokenAsync(user.Id);
                var result = await UserManager.ResetPasswordAsync(user.Id, code, model.Password);
                if (result.Succeeded)
                {
                    //return RedirectToAction("Index", "Home");
                    return Json(true, JsonRequestBehavior.AllowGet);
                }
            }
            //var result = UserManager.ResetPasswordAsync(user.Id, model.Code, model.Password);
            //if (result.Succeeded)
            //{
            //    //return RedirectToAction("ResetPasswordConfirmation", "Account");
            //}
            //AddErrors(result);
            return Json(false, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ChangePassword()
        {
            return View();
        }

        public ActionResult Dashboard()
        {
            return View();
        }
    }
}

EEAFormI9Portal/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EEAFormI9Portal.EF;
using EEAFormI9Portal.Models;
using AutoMapper;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;

namespace EEAFormI9Portal.Controllers
{
    //[Authorize(Roles="systemadmin")]
    public class RolesController : BaseController
    {
        private EEAFORMI9Entities db = new EEAFORMI9Entities();


        [HttpGet]
        public JsonResult GetUserDetails()
        {
            var User = new List<AspNetUser>();
            //var User1 = new List<ViewUserAndRoleDetails>();

            User = _IUserManagement.GetUserAndRoleDetails();
            
            var e = Mapper.Map<List<ViewUserAndRoleDetails>>(User);

            return Json(e, JsonRequestBehavior.AllowGet);

        }


        public ActionResult Dashboard()
        {
            return View();
        }

        // GET: Roles
        public ActionResult Index()
        {
            return View(db.AspNetUsers.ToList());
        }

        // GET: Roles/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        // GET: Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] AspNetUser aspNetUser)
        {
            if (ModelState.IsValid)
            {
                db.AspNetUsers.Add(aspNetUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aspNetUser);
        }

        // GET: Roles/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //var aspNetUser = db.AspNetUsers.Find(id);
            //var aspNetRoles = db.AspNetRoles.ToList();
            //if (aspNetUser == null)
            //{
            //    return HttpNotFound();
            //}
            var model = new UserRoleViewModel()
            {
                Users = db.AspNetUsers.Find(id),
                Roles = db.AspNetRoles.ToList()
            };
            var listItems = new List<SelectListItem>();
            foreach (var role in model.Roles)
            {
                listItems.Add(new SelectListItem
                {
                    Value = role.Id,
                    Text = role.Name
                });
            }
            ViewBag.ListOfRoles = listItems;

            return View(model);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] AspNetUser aspNetUser)
        //public ActionResult Edit(UserRoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aspNetUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aspNetUser);
        }

        // GET: Roles/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            db.AspNetUsers.Remove(aspNetUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult ViewRoleDetails()
        {
            return View();
        }

        [HttpGet]
       // [Authorize(Roles ="sysadmin")]
        public JsonResult GetRoles()
        {
            var role = new List<AspNetRole>();
            //role = _IRoleManagement.GetRoles();
            role = db.AspNetRoles.ToList();
            var e = Mapper.Map<List<ViewRoles>>(role);
            return Json(e, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ViewHrDetails()
        {
            return View();

        }

        [HttpGet]
        public JsonResult GetHrDetails()
        {
            var User = new List<AspNetUser>();
            //var User1 = new List<ViewUserAndRoleDetails>();

            User = _IUserManagement.GetHrDetails();

            var e = Mapper.Map<List<ViewUserAndRoleDetails>>(User);

            return Json(e, JsonRequestBehavior.AllowGet);

        }

        public async Task<JsonResult> updateUserDetails()
        {
            string[] roles = { "representative", "admin" };
            //var currUser = new AspNetUser;
           // Guid id = new Guid("5763912d-3d01-4a27-bd28-935c2c2c9bac");
            var currUser =  await UserManager.FindByIdAsync(User.Identity.GetUserId());

            foreach(var role in roles)
            {
                var roleresult = await UserManager.AddToRoleAsync(currUser.Id.ToString(), role);
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAllRoles()
        {
            //var roles = new List<AspNetRole>();

            //roles = _IRoleManagement.GetAllRoles();
            var roles = Mapper.Map<List<ViewAspNetRoles>>(_IRoleManagement.GetAllRoles());

            return Json(roles, JsonRequestBehavior.AllowGet);


        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EEAFormI9Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @*<!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js"></script>*@


    <link rel="stylesheet"
          href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="http://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <script type="text/javascript"
            src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>

</head>
<body>
    <div id="wrapper">
        <!-- Header start-->
            @Html.Partial("~/Views/Shared/_Navigation.cshtml")
        <!-- Header end-->
        <div class="container-fluid body-content">
            @RenderBody()
            
        </div>
    </div>
    <hr />
    <footer class="footer">
        <div class="container">
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </div>
    </footer>

    
    @RenderSection("scripts", required: false)
</body>
</html>

EEAFormI9Portal/Views/Shared/_Navigation.cshtml
    <div class="navbar navbar-fixed-top" style="background-color:powderblue; border-color:lightgrey;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Computech Corporation", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    @if (Request.IsAuthenticated)
                    {
                        if (User.IsInRole("systemadmin"))
                        {
                            @*<li>@Html.ActionLink("MANAGE", "Index", "Roles")</li>*@
                            <li>@Html.ActionLink("DASHBOARD", "Dashboard", "Roles")</li>
                            @*<li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    MANAGE<span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        @Html.ActionLink("ADMINS", "Index", "Roles")
                                    </li>
                                    <li>
                                        @Html.ActionLink("HR", "ViewHrDetails", "Roles")
                                    </li>
                                    <li>
                                        @Html.ActionLink("ROLES", "ViewRoleDetails", "Roles")
                                    </li>
                                    <li>
                                        @Html.ActionLink("DOCUMENT STATUS", "Index", "Roles")
                                    </li>
                                </ul>
                            </li>*@

                        }
                        else if (User.IsInRole("hr"))
                        {
                            @*<li>@Html.ActionLink("User", "Index", "User")</li>
                                <li>@Html.ActionLink("User", "Index", "User")</li>
                                <li>@Html.ActionLink("User", "Index", "User")</li>*@

                            <li>@Html.ActionLink("DASHBOARD", "Dashboard", "User")</li>

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    MANAGE<span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        @Html.ActionLink("EMPLOYEES", "UserDetails", "User")
                                    </li>
                                    <li>
                                        @Html.ActionLink("REPRESENTATIVES", "RepresentativeDetails", "User")
                                    </li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    DOCUMENT<span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        @Html.ActionLink("DOCUMENT", "Index", "Document")
                                    </li>
                                </ul>
                            </li>

                        }
                        else
                        {
                            <li>@Html.ActionLink("DASHBOARD", "Dashboard", "Employee")</li>
                        }
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>